text_file = open("my_file.txt", "a+")
text_file.write("\nMore lines!!!\n")
text_file.write("Line 7\n")
text_file.write("Line 8\n")
text_file.write("Line 9")
text_file.seek(0)
file_content = text_file.read()
print(file_content)